# Generated by Django 5.0.1 on 2024-01-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0009_alter_medecin_date_naissance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='adresse_cabinet',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tele',
        ),
    ]
