# Generated by Django 5.0.1 on 2024-01-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0010_remove_medecin_adresse_cabinet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='email',
        ),
    ]
