# Generated by Django 5.0.1 on 2024-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0011_remove_medecin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='adresse_cabinet',
            field=models.CharField(default='Valeur par défaut', max_length=200),
        ),
        migrations.AddField(
            model_name='medecin',
            name='date_embauche',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='date_naissance',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='tele',
            field=models.CharField(default='Valeur par défaut', max_length=10),
        ),
    ]
