# Generated by Django 5.0.1 on 2024-01-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0015_alter_medecin_adresse_cabinet_and_more'),
    ]

    operations = [
    ]
