# Generated by Django 5.0.1 on 2024-01-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0016_auto_20240127_2208'),
    ]

    operations = [
    ]
