# Generated by Django 5.0.1 on 2024-01-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0017_auto_20240127_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='heure',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='patient',
        ),
        migrations.AlterField(
            model_name='medecin',
            name='date_embauche',
            field=models.DateField(blank=True, default='2020-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='date_naissance',
            field=models.DateField(blank=True, default='2020-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, default='2024-08-21', null=True),
        ),
    ]
