# Generated by Django 5.0.1 on 2024-01-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0020_medecin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
