# Generated by Django 5.0.1 on 2024-01-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0022_alter_medecin_email_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, null=True),
        ),
    ]
